# Makefile for a basic z80 system
#  This relies heavily on the Common/ includes

TARG := z80emu

include ../Common/defs.mak

# additional defs
CFLAGS += 
SRCS += 


include ../Common/rules.mak

# additional rules
$(BUILD)/m6850_xxx.o:	$(ORIGSRC)/defs.h $(COMMONSRC)/6850_xxx.c
